
# Example  4:

x = 6
try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")
