# Example 1

x=5
try:
    print(x)

except:
    print('Exception occured')





